// <auto-generated />
namespace FitApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addActivityCoachRoomActivityUser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addActivityCoachRoomActivityUser));
        
        string IMigrationMetadata.Id
        {
            get { return "201808231159590_add Activity,Coach,Room,ActivityUser    "; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
